# serverless.yml

service: serverless-nodejs-app

provider:
  name: aws
  runtime: nodejs18.x
  stage: prod
  region: us-east-1

functions:
  app:
    handler: app.handler # reference the file and exported method
    events: # events trigger lambda functions
      - http: # this is an API Gateway HTTP event trigger
          path: /
          method: ANY
          cors: true
      - http: # all routes get proxied to the Express router
          path: /{proxy+}
          method: ANY
          cors: true
